import { describe, it, expect } from 'vitest';
import { generateCSS, tokenToCssVar } from '../css.js';
import { buildRegistry } from '../registry.js';
import { processInput } from '../processor.js';
import { wcag21 } from '../compliance/wcag21.js';
import { hexToColorValue } from '../utils/oklch.js';
import type { TokenInput } from '../types.js';

const cv = (hex: string) => hexToColorValue(hex);

const input: TokenInput = {
  primitives: {
    neutral: [
      '#fafafa', '#f5f5f5', '#e5e5e5', '#d4d4d4',
      '#a3a3a3', '#737373', '#525252', '#404040',
      '#262626', '#171717',
    ].map(cv),
    red: [
      '#fef2f2', '#fee2e2', '#fecaca', '#fca5a5',
      '#f87171', '#ef4444', '#dc2626', '#b91c1c',
      '#991b1b', '#7f1d1d',
    ],
    green: [
      '#f0fdf4', '#dcfce7', '#bbf7d0', '#86efac',
      '#4ade80', '#22c55e', '#16a34a', '#15803d',
      '#166534', '#14532d',
    ],
  },
  themes: {
    white: { ramp: 'neutral', step: 0 },
    dark: { ramp: 'neutral', step: 8 },
  },
  surfaces: {
    bgMain: {
      ramp: 'neutral',
      step: 1,
      interactions: { hover: { step: 2 }, active: { step: 3 } },
    },
    bgInverse: {
      ramp: 'neutral',
      step: 9,
      themes: { dark: { step: 0 } },
    },
  },
  foreground: {
    fgPrimary: { ramp: 'neutral', defaultStep: 8 },
    fgError: {
      ramp: 'red',
      defaultStep: 6,
    },
    fgSuccess: {
      ramp: 'green',
      defaultStep: 6,
    },
    fgLink: {
      ramp: 'neutral',
      defaultStep: 6,
      interactions: {
        hover: { step: 7 },
      },
    },
  },
};

const processed = processInput(input);
const registry = buildRegistry(processed, wcag21);
const css = generateCSS(registry);

describe('tokenToCssVar', () => {
  it('converts camelCase to kebab-case with -- prefix', () => {
    expect(tokenToCssVar('fgPrimary')).toBe('--fg-primary');
    expect(tokenToCssVar('fgSecondary')).toBe('--fg-secondary');
    expect(tokenToCssVar('fgLink')).toBe('--fg-link');
  });

  it('handles interaction suffix', () => {
    expect(tokenToCssVar('fgLink-hover')).toBe('--fg-link-hover');
    expect(tokenToCssVar('fgLink-active')).toBe('--fg-link-active');
  });
});

describe('generateCSS', () => {
  it('produces a non-empty string', () => {
    expect(typeof css).toBe('string');
    expect(css.length).toBeGreaterThan(0);
  });

  it('contains :root block', () => {
    expect(css).toContain(':root {');
  });

  it('contains token vars in :root', () => {
    expect(css).toContain('--fg-primary:');
    expect(css).toContain('--fg-error:');
    expect(css).toContain('--fg-link:');
  });

  it('contains interaction state vars', () => {
    expect(css).toContain('--fg-link-hover:');
  });

  it('contains --bg-* vars in :root', () => {
    expect(css).toContain('--bg-white:');
    expect(css).toContain('--bg-dark:');
  });

  it('contains ramp step vars in :root', () => {
    expect(css).toContain('--neutral-0:');
    expect(css).toContain('--neutral-9:');
  });

  it('contains [data-theme] overrides for non-default themes', () => {
    expect(css).toContain('[data-theme="dark"]');
  });

  it('vision mode block uses correct selector order: [data-theme] before [data-vision]', () => {
    // data-theme is set on <html>, data-vision is on the TokenProvider descendant div.
    // Correct order: [data-theme="X"] [data-vision="Y"] (data-vision inside data-theme).
    // Wrong order:   [data-vision="Y"] [data-theme="X"] (would require data-theme inside data-vision).
    const hasCorrect = /\[data-theme="[^"]+"\] \[data-vision="[^"]+"\]/.test(css);
    const hasWrong = /\[data-vision="[^"]+"\] \[data-theme="[^"]+"\]/.test(css);
    if (hasCorrect || hasWrong) {
      expect(hasCorrect).toBe(true);
      expect(hasWrong).toBe(false);
    }
  });

  it('contains vision mode block', () => {
    // protanopia variants are generated by hue-shifting red/green confused tokens.
    // No auxiliary ramp required — the shift works directly on each token's L and C.
    const hasVision = css.includes('[data-vision="protanopia"]') ||
                      css.includes('[data-vision="deuteranopia"]') ||
                      css.includes('[data-vision="achromatopsia"]');
    expect(hasVision).toBe(true);
  });

  it('does not emit empty blocks', () => {
    // Every { must be followed by at least one var before }
    const blocks = css.split('}');
    for (const block of blocks) {
      const openIdx = block.lastIndexOf('{');
      if (openIdx === -1) continue;
      const content = block.slice(openIdx + 1).trim();
      if (block.slice(0, openIdx).trim() === '') continue; // final empty after last }
      // Content should not be empty if block was opened
      // (only check blocks that have a selector)
      const selector = block.slice(0, openIdx).trim();
      if (selector.length > 0) {
        // Non-empty selector must have content
        // (some edge cases are okay — just ensure we don't have "selector {}"
        if (content.length === 0) {
          // This would be an empty block — fail
          expect(content.length).toBeGreaterThan(0);
        }
      }
    }
  });

  it('only emits standalone [data-theme] block if values differ from :root', () => {
    // white is the default theme — no standalone [data-theme="white"] { block should appear.
    // Vision descendant selectors like [data-vision="X"] [data-theme="white"] are fine.
    // A standalone block starts a new line with [data-theme="white"] at the very beginning.
    const standaloneBlock = /^\[data-theme="white"\]\s*\{/m.test(css);
    expect(standaloneBlock).toBe(false);
  });

  it('emits --bg-main surface var in :root', () => {
    expect(css).toContain('--bg-main:');
  });

  it('emits --bg-inverse surface var in :root', () => {
    expect(css).toContain('--bg-inverse:');
  });

  it('emits surface interaction vars in :root', () => {
    expect(css).toContain('--bg-main-hover:');
    expect(css).toContain('--bg-main-active:');
  });

  it('emits surface theme override in [data-theme="dark"] block', () => {
    // bgInverse has themes: { dark: { step: 0 } } — step 0 (#fafafa) vs default step 9 (#171717)
    // So [data-theme="dark"] must contain --bg-inverse: #fafafa
    const darkBlock = css.split(/\[data-theme="dark"\]\s*\{/)[1]?.split('}')[0] ?? '';
    expect(darkBlock).toContain('--bg-inverse:');
    expect(darkBlock).toContain('#fafafa');
  });
});

describe('surface utility classes', () => {
  it('populates surfaceTokens on each surface after buildRegistry', () => {
    const bgMain = registry.surfaces.get('bgMain')!;
    const bgInverse = registry.surfaces.get('bgInverse')!;
    expect(bgMain.surfaceTokens.size).toBeGreaterThan(0);
    expect(bgInverse.surfaceTokens.size).toBeGreaterThan(0);
  });

  it('resolves fgPrimary to dark text on bgMain (light surface)', () => {
    // bgMain = neutral step 1 = #f5f5f5 (near white) — needs dark text
    const bgMain = registry.surfaces.get('bgMain')!;
    const fgHex = bgMain.surfaceTokens.get('fgPrimary')!;
    expect(fgHex).toBeDefined();
    // Dark text on light bg: relative luminance of resolved step < 0.2
    const r = parseInt(fgHex.slice(1, 3), 16) / 255;
    const g = parseInt(fgHex.slice(3, 5), 16) / 255;
    const b = parseInt(fgHex.slice(5, 7), 16) / 255;
    const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b;
    expect(lum).toBeLessThan(0.2);
  });

  it('resolves fgPrimary to light text on bgInverse (dark surface)', () => {
    // bgInverse = neutral step 9 = #171717 (near black) — needs light text
    const bgInverse = registry.surfaces.get('bgInverse')!;
    const fgHex = bgInverse.surfaceTokens.get('fgPrimary')!;
    expect(fgHex).toBeDefined();
    // Light text on dark bg: relative luminance > 0.5
    const r = parseInt(fgHex.slice(1, 3), 16) / 255;
    const g = parseInt(fgHex.slice(3, 5), 16) / 255;
    const b = parseInt(fgHex.slice(5, 7), 16) / 255;
    const lum = 0.2126 * r + 0.7152 * g + 0.0722 * b;
    expect(lum).toBeGreaterThan(0.5);
  });

  it('bgMain and bgInverse resolve fgPrimary to opposite ends of the ramp', () => {
    const lightFg = registry.surfaces.get('bgMain')!.surfaceTokens.get('fgPrimary')!;
    const darkFg = registry.surfaces.get('bgInverse')!.surfaceTokens.get('fgPrimary')!;
    expect(lightFg).not.toBe(darkFg);
  });

  it('themeSurfaceTokens has dark entry for bgMain (auto-mirror changes hex)', () => {
    // dark theme mirrors bgMain: step 1 → step 8 (#262626) — a dark surface needing light text
    const bgMain = registry.surfaces.get('bgMain')!;
    expect(bgMain.themeSurfaceTokens.has('dark')).toBe(true);
    const darkEntry = bgMain.themeSurfaceTokens.get('dark')!;
    // fgPrimary must differ between light and dark surface hexes
    expect(darkEntry.tokens.get('fgPrimary')).not.toBe(bgMain.surfaceTokens.get('fgPrimary'));
  });

  it('emits .bg-bgMain utility class in CSS', () => {
    expect(css).toContain('.bg-bgMain,');
    expect(css).toContain('.hover\\:bg-bgMain:hover {');
  });

  it('.bg-bgMain contains background var and resolved token vars', () => {
    const classBlock = css.split('.bg-bgMain,')[1]?.split('}')[0] ?? '';
    expect(classBlock).toContain('background: var(--bg-main)');
    expect(classBlock).toContain('--fg-primary:');
  });

  it('emits [data-theme="dark"] override block for .bg-bgMain', () => {
    expect(css).toContain('[data-theme="dark"] .bg-bgMain,');
  });

  it('[data-theme="dark"] .bg-bgMain contains different --fg-primary than default', () => {
    const defaultFg = registry.surfaces.get('bgMain')!.surfaceTokens.get('fgPrimary')!;
    const darkFg = registry.surfaces.get('bgMain')!.themeSurfaceTokens.get('dark')!.tokens.get('fgPrimary')!;
    expect(css).toContain(darkFg);
    expect(defaultFg).not.toBe(darkFg);
  });

  it('does not emit [data-theme] override when surface hex is identical across themes', () => {
    // If a theme happens to resolve to the same surface hex as the default,
    // no override block should be emitted (no noise in CSS).
    for (const [surfaceName, surface] of registry.surfaces) {
      for (const [themeName, { tokens: themeTokens }] of surface.themeSurfaceTokens) {
        const overrides = Array.from(themeTokens)
          .filter(([t, hex]) => hex !== surface.surfaceTokens.get(t));
        if (overrides.length === 0) {
          const pattern = `[data-theme="${themeName}"] .bg-${surfaceName},`;
          expect(css).not.toContain(pattern);
        }
      }
    }
  });
});
